"""Synthetic, labeled examples; never mixed with the real corpus."""
from PIL import Image, ImageDraw, ImageFont

from .colors import best_text
from .recommend import OKABE_ITO, references


def seed_demo(store):
    for kind in ("data", "flowchart"):
        for count in range(3, 9):
            journal = ("Nature", "Science", "Cell")[(count-3) % 3]
            paper_id = f"DEMO-{kind}-{count}"
            store.put_paper({"id": paper_id, "journal": journal, "year": 2021+(count-3)%5,
                "title": f"Synthetic {kind} example · {count} colors (not a journal article)", "is_demo": True,
                "license": "Synthetic illustration generated by this application", "metadata": {"synthetic": True}})
            colors = [{"hex": c, "role": "unassigned"} for c in OKABE_ITO[:count]] if kind == "data" else references(kind, count)[0]["colors"]
            image = Image.new("RGB", (900, 540), "white")
            draw = ImageDraw.Draw(image)
            font = ImageFont.load_default(size=20)
            draw.text((35, 25), "SYNTHETIC EXAMPLE · Not publication data", fill="#64748B", font=font)
            if kind == "data":
                draw.line((65, 85, 65, 440, 850, 440), fill="#17243A", width=2)
                for i,c in enumerate(colors):
                    x = 100+i*720//count
                    h = 100+(i*67)%220
                    draw.rectangle((x, 440-h, x+500//count, 440), fill=c["hex"])
                    draw.text((x, 457), f"Group {i+1}", fill="#17243A", font=font)
            else:
                fills = [c for c in colors if c["role"] in ("fill", "decision")]
                for i in range(max(3,len(fills))):
                    c = fills[i%len(fills)]
                    x = 60+i*750//max(3,len(fills))
                    draw.rounded_rectangle((x,190,x+180,310), radius=16, fill=c["hex"], outline="#64748B", width=2)
                    draw.text((x+25,235), "Decision" if c["role"] == "decision" else f"Process {i+1}", fill=best_text(c["hex"]), font=font)
                    if i < max(3,len(fills))-1:
                        draw.line((x+181,250,x+235,250), fill="#64748B", width=3)
                        draw.polygon((x+235,250,x+226,245,x+226,255), fill="#64748B")
            path = store.root / "assets" / f"{paper_id}.png"
            image.save(path)
            fid, new = store.put_figure(paper_id, "main", "Synthetic example", "Synthetic chart for demonstrating the interface.", path, "", *image.size)
            if new:
                with store.connect() as db:
                    row = db.execute("SELECT id,revision FROM panels WHERE figure_id=?", (fid,)).fetchone()
                store.review(row["id"], {"kind": kind, "palette_type": "categorical" if kind == "data" else "roles",
                    "colors": colors, "eligibility": "included", "confirmed_experimental": True, "revision": row["revision"],
                    "notes": "Synthetic demonstration only; excluded from real-corpus analysis."})
